name: Grammar Review Action
description: 'Reviews Markdown files for grammar using Gemini and reviewdog'
inputs:
  gemini_api_key:
    description: 'Gemini API Key'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args: []
